# Generated by Django 4.1.7 on 2023-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campaign_limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
