# Generated by Django 4.1.7 on 2023-08-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_campaign_limit_reached"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="revenue_distributed",
            field=models.BooleanField(default=False),
        ),
    ]
