# Generated by Django 4.1.7 on 2023-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_revenue_distributed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotion_ends_on",
            field=models.DateTimeField(null=True),
        ),
    ]
