# Generated by Django 4.2.4 on 2023-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_promotion_ends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
