# Generated by Django 4.2.4 on 2023-09-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCampaignPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('min_targetted_age', models.FloatField(default=1)),
                ('max_targetted_age', models.FloatField(default=250)),
                ('target_platforms', models.JSONField(default=list)),
                ('min_followers_on_target_platform', models.IntegerField(default=100)),
                ('min_engagement_percentage', models.FloatField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productpreferences', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
