# Generated by Django 4.2.4 on 2023-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcampaignpreference_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('cars', 'Cars'), ('electronics', 'Electronics'), ('food', 'Food'), ('digital_content', 'Digital Content'), ('houses', 'Houses')], max_length=255, null=True),
        ),
    ]
