# Generated by Django 4.2.5 on 2023-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcampaignpreference',
            name='target_platforms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
