# Generated by Django 4.2.5 on 2023-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcampaignpreference_target_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcampaignpreference',
            name='target_platforms',
            field=models.JSONField(default=list),
        ),
    ]
