# Generated by Django 4.2.5 on 2023-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productcampaignpreference_target_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_targetted_age',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='product',
            name='min_engagement_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_followers_on_target_platform',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='min_targetted_age',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='target_platforms',
            field=models.JSONField(default=list),
        ),
    ]
