# Generated by Django 4.2.5 on 2023-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_max_targetted_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_budget_paid',
            field=models.BooleanField(default=False),
        ),
    ]
