# Generated by Django 4.2.5 on 2023-09-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_billingcategory'),
        ('products', '0015_product_promotion_budget_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.billingcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_period_in',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=255, null=True),
        ),
    ]
