# Generated by Django 4.2.5 on 2023-09-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_max_targetted_age_and_more'),
        ('payments', '0003_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
