# Generated by Django 4.2.5 on 2023-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mpesatransaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='TransactionTimeStamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
