# Generated by Django 4.2.5 on 2023-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaResponseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('response_data', models.JSONField(default=dict)),
                ('response_description', models.CharField(max_length=1000)),
                ('response_code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
