# Generated by Django 4.2.5 on 2023-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_mpesaresponsedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('charge_per_12_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_per_24_hours', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
