# Generated by Django 4.2.5 on 2023-09-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_promotion_package_product_promotion_period_and_more'),
        ('payments', '0008_billingcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('promotion_period', models.CharField(max_length=255)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advert_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.billingcategory')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
