# Generated by Django 4.2.5 on 2023-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_advertisementorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
