# Generated by Django 4.2.5 on 2023-09-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_advertisementorder_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingcategory',
            old_name='charge_per_12_hours',
            new_name='charge_per_hour',
        ),
        migrations.RemoveField(
            model_name='billingcategory',
            name='charge_per_24_hours',
        ),
    ]
