# Generated by Django 4.2.5 on 2023-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_charge_per_12_hours_billingcategory_charge_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementorder',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
