# Generated by Django 4.1.7 on 2023-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_influencer_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
