# Generated by Django 4.1.7 on 2023-08-31 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='facebook',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='instagram',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='threads',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube',
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('instagram', models.CharField(max_length=255, null=True)),
                ('tiktok', models.CharField(max_length=255, null=True)),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('twitter', models.CharField(max_length=255, null=True)),
                ('threads', models.CharField(max_length=255, null=True)),
                ('youtube', models.CharField(max_length=255, null=True)),
                ('telegram', models.CharField(max_length=255, null=True)),
                ('snapchat', models.CharField(max_length=255, null=True)),
                ('whatsapp_number', models.CharField(max_length=255, null=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
