# Generated by Django 4.1.7 on 2023-08-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_influencer_second_photo_influencer_third_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_logo",
            field=models.FileField(null=True, upload_to="customers_logo"),
        ),
    ]
