# Generated by Django 4.2.4 on 2023-09-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customer_customer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preferred_platforms', models.JSONField(default=list)),
                ('min_targetted_age', models.FloatField(default=1)),
                ('max_targetted_age', models.FloatField(default=250)),
                ('preferred_brand_types', models.JSONField(default=list)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
