# Generated by Django 4.2.5 on 2023-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_influencerpreference_influencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpreference',
            name='preferred_brand_types',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpreference',
            name='preferred_platforms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
