# Generated by Django 4.2.5 on 2023-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_influencerpreference_preferred_brand_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpreference',
            name='preferred_brand_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='influencerpreference',
            name='preferred_platforms',
            field=models.JSONField(default=list),
        ),
    ]
