# Generated by Django 4.2.5 on 2023-09-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_influencerpreference_preferred_brand_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=255)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('username', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('profile_photo', models.URLField(max_length=100, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
