# Generated by Django 4.2.5 on 2023-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_influencer_max_targetted_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='minimum_budget_consideration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
