# Generated by Django 4.2.4 on 2023-09-01 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_engagement_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('f38532ad-505f-410e-bf0a-45abef174875'))),
                ('text', models.TextField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.promotioncampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
