# Generated by Django 4.2.4 on 2023-09-04 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_engagementcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('90c56983-42ec-469b-b84d-7f59cad16d27')),
        ),
    ]
