# Generated by Django 4.2.4 on 2023-09-04 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0d440cd5-c1ae-4b63-a85d-83845daf0390')),
        ),
    ]
