# Generated by Django 4.2.4 on 2023-09-04 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_engagement_city_engagement_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d0d7dc3-99e0-4839-bb3c-344fb6971ff1')),
        ),
    ]
