# Generated by Django 4.2.4 on 2023-09-04 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcomment',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engagementcomment',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engagementcomment',
            name='customer_ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engagementcomment',
            name='device_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca3b1cfd-c418-4e53-9e5b-091667a2dd95')),
        ),
    ]
