# Generated by Django 4.2.4 on 2023-09-04 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_engagementcomment_city_engagementcomment_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('87b2804c-8bee-46fa-aa33-aef46d6bf64d')),
        ),
    ]
