# Generated by Django 4.2.4 on 2023-09-04 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_engagement_source_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncampaign',
            name='facebook_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='instagram_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='linkedin_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='snapchat_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='threads_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='tiktok_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='twitter_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='youtube_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4fc518cf-1ea0-4de1-9b7e-785b41ce299d')),
        ),
    ]
