# Generated by Django 4.2.4 on 2023-09-04 11:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_promotioncampaign_email_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('36e1c009-a2cc-4f88-93ec-2e1ea51cde22')),
        ),
    ]
