# Generated by Django 4.2.4 on 2023-09-04 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('589e7108-f61b-43a6-8e66-f8194b791f5b')),
        ),
    ]
