# Generated by Django 4.2.4 on 2023-09-05 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f6e7e6f7-8cc3-4e68-a0e7-b3b1a3523309')),
        ),
    ]
