# Generated by Django 4.2.4 on 2023-09-05 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('209a5140-4809-461a-9e2e-ccbc3d83f125')),
        ),
    ]
