# Generated by Django 4.2.4 on 2023-09-05 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('87e46a34-649b-40dc-a0fc-66055f989786')),
        ),
    ]
