# Generated by Django 4.2.5 on 2023-09-05 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('83ee93e6-dc40-4600-ba5c-96ef956abf62')),
        ),
    ]
