# Generated by Django 4.2.5 on 2023-09-05 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9be40f14-18fe-4649-ab04-fd540f4331e8')),
        ),
    ]
