# Generated by Django 4.2.5 on 2023-09-06 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0029_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48a7478f-5ea9-4683-88e2-cf4c2e038b4a')),
        ),
    ]
