# Generated by Django 4.2.5 on 2023-09-07 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6d6c0c43-4280-4461-ac62-788fce9d32af')),
        ),
    ]
