# Generated by Django 4.2.5 on 2023-09-07 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0031_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7cf8bf4-c208-483e-a714-8b639d29ab20')),
        ),
    ]
