# Generated by Django 4.2.5 on 2023-09-08 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('937ee456-f6c7-4c9a-a9a5-fbf52e31c0fe')),
        ),
    ]
