# Generated by Django 4.2.5 on 2023-09-08 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0035_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f2b1b43-999e-4f8c-922c-f285f92d1abb')),
        ),
    ]
