# Generated by Django 4.2.5 on 2023-09-08 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0036_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b01cf16-7dcb-4fc6-9920-43fa19f5df04')),
        ),
    ]
