# Generated by Django 4.2.5 on 2023-09-08 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d045fdba-c681-4313-8182-79696b1cece7')),
        ),
    ]
