# Generated by Django 4.2.5 on 2023-09-11 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0041_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b853acae-d6ee-4c36-a17a-5ee275c9d82d')),
        ),
    ]
