# Generated by Django 4.2.5 on 2023-09-11 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0042_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3c782f0-4e6d-4ca1-b061-ce3258e90e07')),
        ),
    ]
