# Generated by Django 4.2.5 on 2023-09-11 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0043_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('699735cf-5080-42e1-946b-08dd47e434d8')),
        ),
    ]
