# Generated by Django 4.2.5 on 2023-09-11 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0044_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b3a4d6f-bb4d-4dd3-9674-e573385089f0')),
        ),
    ]
