# Generated by Django 4.2.5 on 2023-09-11 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0045_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('098ecb08-fd88-4082-8916-cd013f421b50')),
        ),
    ]
