# Generated by Django 4.2.5 on 2023-09-11 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0046_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('46a53900-05e2-4823-ab8c-e7eb3a9f4ce5')),
        ),
    ]
