# Generated by Django 4.2.5 on 2023-09-11 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0047_alter_engagementcomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('59a5c783-c85f-41ac-99ab-e6a5ef065c8c')),
        ),
    ]
